repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        types: [text]
        files: ^(helpers/python|.+\.py)$
        exclude: completions/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [--config=test/setup.cfg]
        additional_dependencies: [flake8-bugbear==20.1.4]
        types: [text]
        files: ^(helpers/python|.+\.py)$
        exclude: completions/
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: [--settings-path=test/setup.cfg]
        types: [text]
        files: ^(helpers/python|.+\.py)$
        exclude: completions/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        args: [--config-file=test/setup.cfg]
        # Intentionally not run on helpers/python (support very old versions)
        exclude: completions/
  - repo: https://github.com/scop/pre-commit-shfmt-workaround
    rev: v0
    hooks:
      - id: shfmt
        name: shfmt
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.1]
        entry: shfmt
        args: [-w, -s]
        types: [text]
        files: ^(bash_completion|completions/[^.].*|test/update-test-cmd-list|.+\.sh(\.in)?)$
        exclude: ^completions/Makefile*
  - repo: https://github.com/ryanrhee/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
        args: [-f, gcc]
        types: [text]
        files: ^(bash_completion|completions/.+|test/run*|.+\.sh(\.in)?)$
        exclude: completions/(\.gitignore|Makefile.*)$
        require_serial: false  # We disable SC1090 anyway, so parallel is ok
  - repo: https://github.com/perltidy/perltidy
    rev: cbb4a687dd331db69219599d84d527397402efdd
    hooks:
      - id: perltidy
        types: [text]
        files: ^(helpers/perl|.+\.p[ml])$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.0
    hooks:
      - id: markdownlint
  - repo: local
    hooks:
      - id: perlcritic
        name: perlcritic
        language: perl
        additional_dependencies: [PETDANCE/Perl-Critic-1.138.tar.gz]
        entry: perlcritic
        args: [--quiet, --verbose, "5"]
        types: [text]
        files: ^(helpers/perl|.+\.p[ml])$
      - id: update-test-cmd-list
        name: update-test-cmd-list
        language: script
        entry: test/update-test-cmd-list
        files: ^test/t/.+\.py$
        pass_filenames: false
